{
 "title": "Emoji",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Version (Summary)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(request_count[1m])) without (result,pod,endpoint,instance,job,namespace,service)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Error / Success (Summary)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(request_count{result=\"success\"}[1m]))",
     "legendFormat": "success"
    },
    {
     "expr": "sum(increase(request_count{result=\"failure\"}[1m]))",
     "legendFormat": "failure"
    }
   ]
  },
  {
   "title": "% of errors by service",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "failure_by_service_1m", "legendFormat": "{{service}}" }
   ]
  },
  {
   "title": "Pods (Canary)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(up_version{service=\"emoji-canary\"}) by (version)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Pods (Stable)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(up_version{service=\"emoji-stable\"}) by (version)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Error / Success (Canary)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(request_count{result=\"success\",service=\"emoji-canary\"}[1m]))",
     "legendFormat": "success"
    },
    {
     "expr": "sum(increase(request_count{result=\"failure\",service=\"emoji-canary\"}[1m]))",
     "legendFormat": "failure"
    }
   ]
  },
  {
   "title": "Error / Success (Stable)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(request_count{result=\"success\",service=\"emoji-stable\"}[1m]))",
     "legendFormat": "success"
    },
    {
     "expr": "sum(increase(request_count{result=\"failure\",service=\"emoji-stable\"}[1m]))",
     "legendFormat": "failure"
    }
   ]
  },
  {
   "title": "Canary version",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(request_count_total{service=\"emoji-canary\"}[1m])) by (version)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Stable version",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(request_count_total{service=\"emoji-stable\"}[1m])) by (version)",
     "legendFormat": "{{version}}"
    }
   ]
  }
 ]
}