// Generated file, do not modify manually!

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/nilebox/kanarini/pkg/apis/kanarini/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeCanaryDeployments implements CanaryDeploymentInterface
type FakeCanaryDeployments struct {
	Fake *FakeKanariniV1alpha1
	ns   string
}

var canarydeploymentsResource = schema.GroupVersionResource{Group: "kanarini.nilebox.github.com", Version: "v1alpha1", Resource: "canarydeployments"}

var canarydeploymentsKind = schema.GroupVersionKind{Group: "kanarini.nilebox.github.com", Version: "v1alpha1", Kind: "CanaryDeployment"}

// Get takes name of the canaryDeployment, and returns the corresponding canaryDeployment object, and an error if there is any.
func (c *FakeCanaryDeployments) Get(name string, options v1.GetOptions) (result *v1alpha1.CanaryDeployment, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(canarydeploymentsResource, c.ns, name), &v1alpha1.CanaryDeployment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CanaryDeployment), err
}

// List takes label and field selectors, and returns the list of CanaryDeployments that match those selectors.
func (c *FakeCanaryDeployments) List(opts v1.ListOptions) (result *v1alpha1.CanaryDeploymentList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(canarydeploymentsResource, canarydeploymentsKind, c.ns, opts), &v1alpha1.CanaryDeploymentList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.CanaryDeploymentList{ListMeta: obj.(*v1alpha1.CanaryDeploymentList).ListMeta}
	for _, item := range obj.(*v1alpha1.CanaryDeploymentList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested canaryDeployments.
func (c *FakeCanaryDeployments) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(canarydeploymentsResource, c.ns, opts))

}

// Create takes the representation of a canaryDeployment and creates it.  Returns the server's representation of the canaryDeployment, and an error, if there is any.
func (c *FakeCanaryDeployments) Create(canaryDeployment *v1alpha1.CanaryDeployment) (result *v1alpha1.CanaryDeployment, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(canarydeploymentsResource, c.ns, canaryDeployment), &v1alpha1.CanaryDeployment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CanaryDeployment), err
}

// Update takes the representation of a canaryDeployment and updates it. Returns the server's representation of the canaryDeployment, and an error, if there is any.
func (c *FakeCanaryDeployments) Update(canaryDeployment *v1alpha1.CanaryDeployment) (result *v1alpha1.CanaryDeployment, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(canarydeploymentsResource, c.ns, canaryDeployment), &v1alpha1.CanaryDeployment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CanaryDeployment), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeCanaryDeployments) UpdateStatus(canaryDeployment *v1alpha1.CanaryDeployment) (*v1alpha1.CanaryDeployment, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(canarydeploymentsResource, "status", c.ns, canaryDeployment), &v1alpha1.CanaryDeployment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CanaryDeployment), err
}

// Delete takes name of the canaryDeployment and deletes it. Returns an error if one occurs.
func (c *FakeCanaryDeployments) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(canarydeploymentsResource, c.ns, name), &v1alpha1.CanaryDeployment{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCanaryDeployments) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(canarydeploymentsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.CanaryDeploymentList{})
	return err
}

// Patch applies the patch and returns the patched canaryDeployment.
func (c *FakeCanaryDeployments) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.CanaryDeployment, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(canarydeploymentsResource, c.ns, name, data, subresources...), &v1alpha1.CanaryDeployment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CanaryDeployment), err
}
