// Generated file, do not modify manually!

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/nilebox/kanarini/pkg/apis/kanarini/v1alpha1"
	scheme "github.com/nilebox/kanarini/pkg/client/clientset_generated/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// CanaryDeploymentsGetter has a method to return a CanaryDeploymentInterface.
// A group's client should implement this interface.
type CanaryDeploymentsGetter interface {
	CanaryDeployments(namespace string) CanaryDeploymentInterface
}

// CanaryDeploymentInterface has methods to work with CanaryDeployment resources.
type CanaryDeploymentInterface interface {
	Create(*v1alpha1.CanaryDeployment) (*v1alpha1.CanaryDeployment, error)
	Update(*v1alpha1.CanaryDeployment) (*v1alpha1.CanaryDeployment, error)
	UpdateStatus(*v1alpha1.CanaryDeployment) (*v1alpha1.CanaryDeployment, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.CanaryDeployment, error)
	List(opts v1.ListOptions) (*v1alpha1.CanaryDeploymentList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.CanaryDeployment, err error)
	CanaryDeploymentExpansion
}

// canaryDeployments implements CanaryDeploymentInterface
type canaryDeployments struct {
	client rest.Interface
	ns     string
}

// newCanaryDeployments returns a CanaryDeployments
func newCanaryDeployments(c *KanariniV1alpha1Client, namespace string) *canaryDeployments {
	return &canaryDeployments{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the canaryDeployment, and returns the corresponding canaryDeployment object, and an error if there is any.
func (c *canaryDeployments) Get(name string, options v1.GetOptions) (result *v1alpha1.CanaryDeployment, err error) {
	result = &v1alpha1.CanaryDeployment{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("canarydeployments").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of CanaryDeployments that match those selectors.
func (c *canaryDeployments) List(opts v1.ListOptions) (result *v1alpha1.CanaryDeploymentList, err error) {
	result = &v1alpha1.CanaryDeploymentList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("canarydeployments").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested canaryDeployments.
func (c *canaryDeployments) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("canarydeployments").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a canaryDeployment and creates it.  Returns the server's representation of the canaryDeployment, and an error, if there is any.
func (c *canaryDeployments) Create(canaryDeployment *v1alpha1.CanaryDeployment) (result *v1alpha1.CanaryDeployment, err error) {
	result = &v1alpha1.CanaryDeployment{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("canarydeployments").
		Body(canaryDeployment).
		Do().
		Into(result)
	return
}

// Update takes the representation of a canaryDeployment and updates it. Returns the server's representation of the canaryDeployment, and an error, if there is any.
func (c *canaryDeployments) Update(canaryDeployment *v1alpha1.CanaryDeployment) (result *v1alpha1.CanaryDeployment, err error) {
	result = &v1alpha1.CanaryDeployment{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("canarydeployments").
		Name(canaryDeployment.Name).
		Body(canaryDeployment).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *canaryDeployments) UpdateStatus(canaryDeployment *v1alpha1.CanaryDeployment) (result *v1alpha1.CanaryDeployment, err error) {
	result = &v1alpha1.CanaryDeployment{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("canarydeployments").
		Name(canaryDeployment.Name).
		SubResource("status").
		Body(canaryDeployment).
		Do().
		Into(result)
	return
}

// Delete takes name of the canaryDeployment and deletes it. Returns an error if one occurs.
func (c *canaryDeployments) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("canarydeployments").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *canaryDeployments) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("canarydeployments").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched canaryDeployment.
func (c *canaryDeployments) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.CanaryDeployment, err error) {
	result = &v1alpha1.CanaryDeployment{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("canarydeployments").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
