// Generated file, do not modify manually!

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	kanariniv1alpha1 "github.com/nilebox/kanarini/pkg/apis/kanarini/v1alpha1"
	clientset "github.com/nilebox/kanarini/pkg/client/clientset_generated/clientset"
	internalinterfaces "github.com/nilebox/kanarini/pkg/client/informers_generated/externalversions/internalinterfaces"
	v1alpha1 "github.com/nilebox/kanarini/pkg/client/listers_generated/kanarini/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// CanaryDeploymentInformer provides access to a shared informer and lister for
// CanaryDeployments.
type CanaryDeploymentInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.CanaryDeploymentLister
}

type canaryDeploymentInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewCanaryDeploymentInformer constructs a new informer for CanaryDeployment type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewCanaryDeploymentInformer(client clientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredCanaryDeploymentInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredCanaryDeploymentInformer constructs a new informer for CanaryDeployment type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredCanaryDeploymentInformer(client clientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KanariniV1alpha1().CanaryDeployments(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KanariniV1alpha1().CanaryDeployments(namespace).Watch(options)
			},
		},
		&kanariniv1alpha1.CanaryDeployment{},
		resyncPeriod,
		indexers,
	)
}

func (f *canaryDeploymentInformer) defaultInformer(client clientset.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredCanaryDeploymentInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *canaryDeploymentInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&kanariniv1alpha1.CanaryDeployment{}, f.defaultInformer)
}

func (f *canaryDeploymentInformer) Lister() v1alpha1.CanaryDeploymentLister {
	return v1alpha1.NewCanaryDeploymentLister(f.Informer().GetIndexer())
}
